### ISSUE TITLE
Success with 1.0.0.39 bootloader

### ISSUE THREAD

**Issue by diggerbonk** [NWSpitfire/AP121-OpenWRT-Install#2]
Just wanted to let you know I was able to install OpenWRT on an AP121 with the 1.0.0.39 bootloader 

```
ar7240> version

Aerohive Boot Loader v1.0.0.39, Build time Mon Dec 23 11:54:09 2013

ar7240>
```

Using the following instructions:

1) Connect to the AP's serial port (9600 8N1)
2) Press space to interrupt the boot process
3) Enter the password (either 'administrator' or 'AhNf?d@ta06')
4) Execute the following commands:

```
dhcp; 
setenv serverip 192.168.0.12; 
tftpboot 0x81000000 openwrt-23.05.0-ath79-nand-aerohive_hiveap-121-squashfs-factory.bin; 
// Make note of the size returned by above commmend (eg 0x9a0000)
nand erase 0x800000 <size>; 
nand write 0x81000000 0x800000 <size>; 
reset;
```

5) Press return to activate the console, you should see:
```

 _______                     ________        __
|       |.-----.-----.-----.|  |  |  |.----.|  |_
|   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
|_______||   __|_____|__|__||________||__|  |____|
         |__| W I R E L E S S   F R E E D O M
-----------------------------------------------------
```

6) Edit /etc/config/network so that eth0 uses dhcp:

  config interface 'loopback'
       option ifname 'lo'
       option proto 'static'
       option ipaddr '127.0.0.1'
       option netmask '255.0.0.0'
  config globals 'globals'
       option ula_prefix 'fd5c:8cdc:2566::/48'
  config interface 'lan'
       option type 'bridge'
       option ifname 'eth0'
       option proto 'dhcp'  
7) Reboot

You should now be able to access the web based configuration dashboard where you can set up the wifi radios, set a root password, etc.

**Comment by NWSpitfire** [comment]
Many thanks for publishing this, I have added to the README with credit. It's great to know the older versions should be compatible on the Hive's.

Glad you got your HiveAP working!
